# Generated by Django 3.2.2 on 2022-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(default='SOME STRING', max_length=2)),
                ('artscraft', models.CharField(default='SOME STRING', max_length=2)),
                ('singing', models.CharField(default='SOME STRING', max_length=2)),
                ('acting', models.CharField(default='SOME STRING', max_length=2)),
                ('readingbooks', models.CharField(default='SOME STRING', max_length=2)),
                ('dancing', models.CharField(default='SOME STRING', max_length=2)),
                ('other', models.CharField(default='SOME STRING', max_length=2)),
            ],
        ),
    ]
